name: "Project Cyrodiil exterior issue"
description: "Problem with exterior landscape or object placement in Project Cyrodiil"
labels: ["Project:Cyrodiil", "exterior"]
body:
- type: markdown
  attributes:
    value: "Describe the issue with the exterior you have"
